title: Thamolwan Poopradubsil
description: Dream big, like reaching for the moon. Even if you don't make it, you'll still find yourself surrounded by the stars.
logo: /assets/img/avatar.png

social-network-links:
  email: "tmw.poopradubsil@gmail.com"
  github: thamolwanpo
  linkedin: thamolwan-poopradubsil

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one