title: Thamolwan Poopradubsil
description: Independent Researcher<br/>M.Sc. Computer Science, NCU Taiwan
logo: /assets/img/avatar.png

social-network-links:
  email: "tmw.poopradubsil@gmail.com"
  github: thamolwanpo
  linkedin: thamolwan-poopradubsil

show_downloads: true
cv_path: /document/Thamolwan_CV.pdf

github:
  is_user_page: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one